### ISSUE TITLE
Bugs Hide and Seek

### ISSUE THREAD

**Issue by DuaneDave** [binhussen/portfolio#13]
Hey @binhussen 👋 

I have gone through your repository and I must commend your effort in putting this together 😄 

pls use a forEach statement to create modal pop-up instead of hard coding a loop 6 times

**Comment by binhussen** [comment]
Thank you @DuaneDave  for your feedback, I have updated the changes as requested and made the fixes we discussed [Link](https://github.com/binhussen/portfolio/) here
