### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by juanmanuelbyc** [binhussen/portfolio#7]
Here we are sharing some feedback from the morning session team regarding Mohamed's code:

- Please try using some comments to separate sections of code in html index file rather than leaving space lines by themselves.
- kindly add reusable class names instead of fixed class name for css

**Comment by binhussen** [comment]
Thank you @kidde60 and @juanmanuelbyc for your feedback, I have updated the changes as requested and made the fixes we discussed [Link](https://github.com/binhussen/portfolio/) here
